/**
 * A cuss is a YUL error or warning.
 * The yul.js program uses them as well.
 *
 * Each cuss has a hexadecimal identification number (aka the "serial"), a flag indicating whether it is fatal or not,
 * and a message.
 */
export interface Cuss {
  readonly serial: number
  readonly fatal: boolean
  readonly message: string
}

/**
 * A use of a cuss.
 * Contains an optional Error if the cuss was caused by an exception.
 * Contains an optional array of strings that may give more information about the circumstances that caused the cuss.
 */
export interface CussInstance {
  cuss: Cuss
  error?: Error
  context?: string[]
}

/**
 * A collection of cusses for a card.
 */
export class Cusses {
  private readonly instances: CussInstance[]

  constructor () {
    this.instances = []
  }

  add (cuss: Cuss): Cusses
  add (cuss: Cuss, ...context: string[]): Cusses
  add (cuss: Cuss, ...context: string[]): Cusses {
    this.instances.push({ cuss, context })
    return this
  }

  addError (cuss: Cuss, error: Error): Cusses
  addError (cuss: Cuss, error: Error, ...context: string[]): Cusses
  addError (cuss: Cuss, error: Error, ...context: string[]): Cusses {
    this.instances.push({ cuss, error, context })
    return this
  }

  addAll (other?: Cusses): Cusses {
    (other?.instances ?? []).forEach(instance => this.instances.push(instance))
    return this
  }

  cusses (): CussInstance[] {
    return this.instances
  }

  empty (): boolean {
    return this.instances.length === 0
  }
}

/**
 * Returns true iff the specified object is a Cuss.
 *
 * @param obj the possible cuss
 * @returns true iff the specified object is a Cuss
 */
export function isCuss (obj: any): obj is Cuss {
  return obj !== undefined && (obj as Cuss).serial !== undefined
}

/**
 * Returns true iff the specified object is a CussInstance.
 *
 * @param obj the possible cuss
 * @returns true iff the specified object is a CussInstance
 */
export function isCussInstance (obj: any): obj is CussInstance {
  return obj !== undefined && (obj as CussInstance).cuss !== undefined
}

function cuss (serial: number, fatal: boolean, message: string): Cuss {
  return { serial, fatal, message }
}

//
// Ref SYM, III-25 - III - 28.
//
// Fault Messages Generated by Assembler
// Card Format
export const Cuss01 = cuss(0x02, false, 'Queer information in column 17')
export const Cuss02 = cuss(0x02, false, 'Queer information at end of line')
// Erasable Problems
export const Cuss03 = cuss(0x03, false, 'EBANK/SBANK illegal except with BBCON & 2CADR')
export const Cuss04 = cuss(0x04, false, 'EBANK conflict with one-shot declaration')
// Polish Opcode Problems
// 05 Erased region shouLd not cross E-banks
export const Cuss06 = cuss(0x06, true, 'Polish words require blanks in columns 1, 17, & 24')
// 07 x Previous Polish equation noi concluded properly
// 08 x Polish push-up requires negative word here
export const Cuss09 = cuss(0x09, false, 'Polish address expected here')
export const Cuss0A = cuss(0x0A, true, 'Asterisk illegal on this opcode')
// 0B x Interpretive instruction not expected
// 0C x Rt-opcodes mode-in disagrees with mode-out setting
// 0D x Lft-opcodes mode-in disagrees with mode-out setting
export const Cuss0E = cuss(0x0E, false, 'Address has no associated polish opcode')
export const Cuss0F = cuss(0x0F, false, 'Polish address(es) missing prior to this op pair')
// 10 x Location symbol improper on STADR'ed store word.
export const Cuss11 = cuss(0x11, true, 'Store opcode must be next after "STADR"')
// 12 x Push-up illegal before store opcode without "STADR"
// 13 Address words cross over bank or VAC area boundary
export const Cuss14 = cuss(0x14, true, 'Interpretive address word out of sequence')
export const Cuss15 = cuss(0x15, true, 'Address field should contain a Polish operator')
export const Cuss16 = cuss(0x16, true, 'First Polish operator illegally indexed')
export const Cuss17 = cuss(0x17, true, 'Interpreter opcode requires indexed address here')
export const Cuss18 = cuss(0x18, true, 'Interpreter opcode did not call for indexing')
// 19 x Second Polish operator illegally indexed
// 1A x Can not hand1e neg addresses with indexing here
// Numeric Constant Problems
export const Cuss1B = cuss(0x1B, false, 'More than 14 octal digits in octal constant')
export const Cuss1C = cuss(0x1C, false, 'More than 10 decimal digits in decimal constant')
export const Cuss1D = cuss(0x1D, false, 'Fractional part lost by truncation')
export const Cuss1E = cuss(0x1E, true, 'Range error in constant field')
// 1F Inexact decimal-to-binary conversion
// 20 Double precision constant should not cross banks
export const Cuss21 = cuss(0x21, false, 'No "D" in decimal number')
// Merge Control Problems
// 22 x Subroutine name not recognized
// 23 Multiple calls in one program or subroutine
// 24 x Card ignored because it makes memory table too long
// 25 x Card ignored because it's too late in the deck
export const Cuss26 = cuss(0x26, true, 'Conflict with earlier use of this address')
export const Cuss27 = cuss(0x27, false, 'Card number out of sequence')
// 28 x No natch found for second card number
// 29 x First card number not less than second
export const Cuss2A = cuss(0x2A, true, 'No match found for card number or acceptor text')
// General Address Field Problems
export const Cuss2B = cuss(0x2B, false, 'Blank address field expected')
export const Cuss2C = cuss(0x2C, true, 'Address field is undefined')
export const Cuss2D = cuss(0x2D, true, 'Address field was undefined in pass1')
// 2D x Address field was undefined in pass1
export const Cuss2E = cuss(0x2E, false, 'Address field should be symbolic')
// 2F x Address field was nearly defiled by equals
// 30 x Address field was nearly defined by equals in pass1
export const Cuss31 = cuss(0x31, true, 'Address field given multiple definitions')
// 32 x Address field multiply defined including by equals
// 33 x Address field multiply defined including nearly by ='s
export const Cuss34 = cuss(0x34, true, 'Address given oversize definition')
export const Cuss35 = cuss(0x35, true, 'Address field is associated with conflict')
// 36 x Address field associated with multiple errors
export const Cuss37 = cuss(0x37, true, 'Address is associated with wrong memory type')
// 38 x Address field is in miscellaneous trouble
export const Cuss39 = cuss(0x39, true, 'Address is inappropriate for opcode')
export const Cuss3A = cuss(0x3A, true, 'Address is in wrong bank')
export const Cuss3B = cuss(0x3B, true, 'Address depends on unknown location')
// 3C Irregular but acceptable address
export const Cuss3D = cuss(0x3D, true, 'Address field is meaningless')
export const Cuss3E = cuss(0x3E, true, 'Addr. must be basic single-precision constant or inst')
export const Cuss3F = cuss(0x3F, true, 'Range error in value of address')
export const Cuss40 = cuss(0x40, true, 'Indexing is illegal here')
export const Cuss41 = cuss(0x41, true, 'Illegal or mis-spelled operation field')
// 42 This instruction should be indexed
export const Cuss43 = cuss(0x43, true, 'This operation should be extended')
export const Cuss44 = cuss(0x44, true, 'This operation should not be extended')
// Predefinition problems
// 45 x Predefinition shouldn't have been predefined
// 46 x Attempt to predefine location symbol failed
// Location Field Problems
export const Cuss47 = cuss(0x47, false, 'Illegal location field format')
export const Cuss48 = cuss(0x48, false, 'Location field should be blank')
// 49 x Location is in wrong type of memory
export const Cuss4A = cuss(0x4A, true, 'Numeric location field is illegal here')
export const Cuss4B = cuss(0x4B, true, 'Oversized or ill-defined location')
export const Cuss4C = cuss(0x4C, true, 'Conflict in use of this location')
// 4D x Location won't fit in symbol table
export const Cuss4E = cuss(0x4E, true, 'No such bank or block number in this machine')
export const Cuss4F = cuss(0x4F, true, 'This bank or block is full')
// Leftover Problems
// 50 x Leftover is indefinitely leftover
// 51 x Leftover won't fit in memory
// 52 x Improper leftover location field format
// More Cusses
export const Cuss53 = cuss(0x53, false, 'Queer information in column 1')
// 54 Address field arithmetic not allowed here
// 55 Address constant not expected here
export const Cuss56 = cuss(0x56, false, 'Address constant expected here')
// 57 Count table full. Address field ignored,
export const Cuss58 = cuss(0x58, true, 'BBANK type constants require preceding EBANK=')
// 59 One shot SBANK= above was not needed
// 5A Address 00,0000 (fi11ed in with address)
// 59 "STADR unnecessary"
export const Cuss5C = cuss(0x5C, false, 'Assembler finds error but has no specific cuss for it')
// 5D x Address is in super bank O (filled in with bank)
